const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/weeklyRecipes.json');
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
let nextId = 1000 + existing.length;
const id = () => nextId++;

const newRecipes = [

// ── FØTEX (8 single-chain) ────────────────────────────────────────────────
{
  id: id(), title: 'Leverpostej med Rugbrød og Rødbeder',
  emoji: '🌿', time: '15 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Klassisk dansk frokost med hjemmelavet leverpostej på mørkt rugbrød toppet med syltede rødbeder og sprøde agurker. Hurtig at lave og fyldig nok til en let aftensmad. En hverdagsfavorit der aldrig går af mode.',
  ingredients: [
    { text: 'Leverpostej 200 g', store: 'Føtex', price: '22 kr.', isPantry: false },
    { text: 'Rugbrød halvt brød', store: 'Føtex', price: '18 kr.', isPantry: false },
    { text: 'Rødbeder syltet 1 glas', store: 'Føtex', price: '14 kr.', isPantry: false },
    { text: 'Agurkeskiver', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær rugbrødet i tykke skiver og smør et generøst lag leverpostej på.',
    'Top med syltede rødbedeskiver og friske agurkeskiver.',
    'Krydr med lidt salt og peber. Server straks.',
  ],
  tip: 'Rist rugbrødet let inden belægning for en dejlig sprød bund.',
  dealItems: [
    { name: 'Leverpostej 200 g', store: 'Føtex', price: '22 kr.' },
    { name: 'Rugbrød', store: 'Føtex', price: '18 kr.' },
    { name: 'Rødbeder syltet', store: 'Føtex', price: '14 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Grillet Laks med Asparges og Citronsauce',
  emoji: '🐟', time: '25 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Saftig laksesteak grillet til perfektion serveret med sprøde grønne asparges og en frisk smørsauce med citron. En elegant men enkel ret til en særlig aften. Klar på under 30 minutter.',
  ingredients: [
    { text: 'Laksesteak 2 stk. 300 g', store: 'Føtex', price: '48 kr.', isPantry: false },
    { text: 'Grønne asparges 1 bundt', store: 'Føtex', price: '22 kr.', isPantry: false },
    { text: 'Smør 50 g', store: 'Føtex', price: '12 kr.', isPantry: false },
    { text: 'Citron 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 1 fed', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Krydr laksen med salt og peber. Grill eller steg den 3-4 minutter på hver side.',
    'Blancher aspargesene i kogende saltet vand i 2 minutter, hæld koldt vand over.',
    'Smelt smørret med hvidløg, tilsæt citronsaft og lad det boble 1 minut.',
    'Server laksen med asparges og hæld citronsaucen over.',
  ],
  tip: 'Bræk de træede ender af aspargesene ved at bøje dem – de knækker naturligt det rigtige sted.',
  dealItems: [
    { name: 'Laksesteak 300 g', store: 'Føtex', price: '48 kr.' },
    { name: 'Grønne asparges', store: 'Føtex', price: '22 kr.' },
    { name: 'Smør 50 g', store: 'Føtex', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Pasta med Pesto, Cherrytomater og Mozzarella',
  emoji: '🍝', time: '20 minutter', servings_count: 2,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'Simpel og lækker pastarett med frisk basilikumpesto, saftige cherrytomater og bløde mozzarellaklatter. Perfekt til en hurtig vegetarisk hverdagsret. Server med ekstra parmesan for den ultimative smag.',
  ingredients: [
    { text: 'Pasta penne 300 g', store: 'Føtex', price: '14 kr.', isPantry: false },
    { text: 'Basilikumpesto 130 g glas', store: 'Føtex', price: '26 kr.', isPantry: false },
    { text: 'Cherrytomater 250 g', store: 'Føtex', price: '18 kr.', isPantry: false },
    { text: 'Mozzarella 125 g', store: 'Føtex', price: '20 kr.', isPantry: false },
    { text: 'Parmesan revet', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Kog pasta efter pakkens anvisning. Gem lidt pastavand.',
    'Halvér cherrytomaterne. Steg dem i olivenolie 2 minutter til de er let bløde.',
    'Vend den varme pasta med pesto. Tilsæt lidt pastavand for at løsne saucen.',
    'Anret med cherrytomater og revet mozzarella. Drys parmesan over og server.',
  ],
  tip: 'Varm aldrig pestoen i panden – tilsæt den direkte til den varme pasta så den bibeholder sin friske smag.',
  dealItems: [
    { name: 'Pasta penne 300 g', store: 'Føtex', price: '14 kr.' },
    { name: 'Basilikumpesto', store: 'Føtex', price: '26 kr.' },
    { name: 'Cherrytomater 250 g', store: 'Føtex', price: '18 kr.' },
    { name: 'Mozzarella 125 g', store: 'Føtex', price: '20 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Kyllingesalat med Avocado og Sennepsdressing',
  emoji: '🥗', time: '20 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En frisk og mættende salat med saftig kyllingebryst, cremet avocado og en syrlig sennepsdressing. Let og nærende – perfekt til frokost eller en let aftensmad. Klar på 20 minutter.',
  ingredients: [
    { text: 'Kyllingebryst 2 stk.', store: 'Føtex', price: '42 kr.', isPantry: false },
    { text: 'Avocado 2 stk.', store: 'Føtex', price: '24 kr.', isPantry: false },
    { text: 'Blandede salater 150 g', store: 'Føtex', price: '18 kr.', isPantry: false },
    { text: 'Dijonsennep 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Olivenolie 3 spsk.', store: null, price: null, isPantry: true },
    { text: 'Æbleeddike 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Honning 1 tsk.', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Krydr kyllingebrysterne med salt og peber. Steg dem i olivenolie 5-6 minutter på hver side til gennemstegte. Lad dem hvile 5 minutter.',
    'Pisk sennep, olivenolie, eddike og honning til en dressing. Smag til med salt og peber.',
    'Skær avocadoen i skiver. Snit kyllingen i strimler.',
    'Anret salat i skåle, top med kylling og avocado, dryp dressingen over.',
  ],
  tip: 'Kyllingen kan sagtens koges i stedet for steges – læg den i vand med laurbær i 15 minutter for en saftig resultat.',
  dealItems: [
    { name: 'Kyllingebryst 2 stk.', store: 'Føtex', price: '42 kr.' },
    { name: 'Avocado 2 stk.', store: 'Føtex', price: '24 kr.' },
    { name: 'Blandede salater 150 g', store: 'Føtex', price: '18 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Oksekødsgryde med Rodfrugter og Rosmarin',
  emoji: '🌿', time: '60 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En kraftig oksekødsgryde med møre rodfrugter og duften af frisk rosmarin. Sæt den over ved lav varme og lad den passe sig selv mens du slapper af. Perfekt til kolde aftener og endnu bedre som rester.',
  ingredients: [
    { text: 'Oksegrydekød 600 g', store: 'Føtex', price: '65 kr.', isPantry: false },
    { text: 'Gulerødder 4 stk.', store: 'Føtex', price: '10 kr.', isPantry: false },
    { text: 'Pastinakker 2 stk.', store: 'Føtex', price: '12 kr.', isPantry: false },
    { text: 'Kartofler 500 g', store: 'Føtex', price: '10 kr.', isPantry: false },
    { text: 'Løg 2 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Oksefond 5 dl', store: null, price: null, isPantry: true },
    { text: 'Rosmarin frisk', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær kødet i tern og brun det i portioner i olie i en stor gryde. Tag det op.',
    'Svits løg og hvidløg i samme gryde 3 minutter.',
    'Læg kødet tilbage. Tilsæt fond, rosmarin og lad det simre 30 minutter med låg.',
    'Tilsæt rodfrugter og kartofler i grove stykker. Kog videre 20 minutter til alt er mørt.',
    'Smag til med salt og peber. Server med godt brød.',
  ],
  tip: 'Jo længere tid gryden simrer, desto mere mørt bliver kødet. 2 timer ved lav varme giver det bedste resultat.',
  dealItems: [
    { name: 'Oksegrydekød 600 g', store: 'Føtex', price: '65 kr.' },
    { name: 'Gulerødder 4 stk.', store: 'Føtex', price: '10 kr.' },
    { name: 'Pastinakker 2 stk.', store: 'Føtex', price: '12 kr.' },
    { name: 'Kartofler 500 g', store: 'Føtex', price: '10 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Torsk med Sennepssauce og Dampet Broccoli',
  emoji: '🐟', time: '25 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Mild torsk bagt i ovnen med en cremet sennepssauce og dampet broccoli. En sund og lækker ret der er klar på 25 minutter. Perfekt til den travle hverdag hvor du stadig vil spise ordentligt.',
  ingredients: [
    { text: 'Torsk filet 400 g', store: 'Føtex', price: '52 kr.', isPantry: false },
    { text: 'Broccoli 1 hoved', store: 'Føtex', price: '15 kr.', isPantry: false },
    { text: 'Piskefløde 1 dl', store: 'Føtex', price: '12 kr.', isPantry: false },
    { text: 'Dijonsennep 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Smør 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Citronsaft', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 180°C. Krydr torskfileten med salt og peber og bag den i ovnen 15 minutter.',
    'Lav saucen: smelt smørret, tilsæt fløde og sennep og lad det simre 3-4 minutter til den er cremet.',
    'Smag saucen til med citronsaft, salt og peber.',
    'Damp broccolibuketter i 4-5 minutter.',
    'Server torsken med sennepssauce og dampet broccoli.',
  ],
  tip: 'Torsk er gennemstegt når den løsner sig i flager ved et let tryk med en gaffel.',
  dealItems: [
    { name: 'Torsk filet 400 g', store: 'Føtex', price: '52 kr.' },
    { name: 'Broccoli 1 hoved', store: 'Føtex', price: '15 kr.' },
    { name: 'Piskefløde 1 dl', store: 'Føtex', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Svinekoteletter med Æblemos og Kartoffelmos',
  emoji: '🌿', time: '35 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Klassiske stegte svinekoteletter serveret med syrlig hjemmelavet æblemos og cremet kartoffelmos. En typisk dansk hverdagsret der smager af barndom og velstand. Nem og billig at lave til hele familien.',
  ingredients: [
    { text: 'Svinekoteletter 4 stk.', store: 'Føtex', price: '44 kr.', isPantry: false },
    { text: 'Æbler 4 stk.', store: 'Føtex', price: '18 kr.', isPantry: false },
    { text: 'Kartofler 1 kg', store: 'Føtex', price: '12 kr.', isPantry: false },
    { text: 'Smør 50 g', store: null, price: null, isPantry: true },
    { text: 'Mælk 1 dl', store: null, price: null, isPantry: true },
    { text: 'Sukker 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skræl og tern æblerne. Kog dem med lidt sukker og 2 spsk vand til de er bløde. Mos dem groft.',
    'Kog kartoflerne møre, afvand og mos dem med smør og varm mælk. Krydr med salt.',
    'Krydr koteletterne med salt og peber. Steg dem i smør 4-5 minutter på hver side til gyldne og gennemstegte.',
    'Server koteletterne med varm æblemos og kartoffelmos.',
  ],
  tip: 'Skær et par snit i kanten af koteletterne inden stegning – det forhindrer dem i at krølle.',
  dealItems: [
    { name: 'Svinekoteletter 4 stk.', store: 'Føtex', price: '44 kr.' },
    { name: 'Æbler 4 stk.', store: 'Føtex', price: '18 kr.' },
    { name: 'Kartofler 1 kg', store: 'Føtex', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Cremet Butternut Squashsuppe med Ingefær',
  emoji: '🫒', time: '40 minutter', servings_count: 4,
  category: 'Middelhavet', cuisine: '🇬🇷 Middelhavet',
  description: 'En silkeblød og krydret squashsuppe med ingefær og kokosmælk der varmer på alle de rigtige steder. Naturligt vegansk og fyldt med smag. Server med ristede solsikkekerner og et dryp olivenolie.',
  ingredients: [
    { text: 'Butternut squash 1 kg', store: 'Føtex', price: '22 kr.', isPantry: false },
    { text: 'Kokosmælk 400 ml', store: 'Føtex', price: '22 kr.', isPantry: false },
    { text: 'Ingefær frisk 2 cm', store: 'Føtex', price: '8 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Grøntsagsbouillon 8 dl', store: null, price: null, isPantry: true },
    { text: 'Gurkemeje og karry', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær squashen i tern og svits med løg, hvidløg og ingefær i olivenolie 5 minutter.',
    'Tilsæt gurkemeje og karry og rør 1 minut.',
    'Tilsæt bouillon og kog 20 minutter til squashen er blød.',
    'Tilsæt kokosmælk og blend suppen glat med en stavblender.',
    'Smag til med salt og peber. Server med ristede solsikkekerner og olivenolie.',
  ],
  tip: 'Rist squashen i ovnen ved 200°C i 25 minutter inden brug for en dybere, karamelliseret smag.',
  dealItems: [
    { name: 'Butternut squash 1 kg', store: 'Føtex', price: '22 kr.' },
    { name: 'Kokosmælk 400 ml', store: 'Føtex', price: '22 kr.' },
    { name: 'Ingefær frisk', store: 'Føtex', price: '8 kr.' },
  ],
  dietaryFilters: ['Vegansk', 'Vegetar'], difficulty: 'nem',
},

// ── ALDI (10 single-chain) ────────────────────────────────────────────────
{
  id: id(), title: 'Wiener Schnitzel med Kartoffelsalat',
  emoji: '🌿', time: '35 minutter', servings_count: 2,
  category: 'Europæisk', cuisine: '🇩🇰 Nordisk',
  description: 'Sprøde, gyldne schnitzler af svinekød paneret i rasp og stegt i smør serveret med en klassisk dansk kartoffelsalat med mayonnaise og purløg. En folkekær ret der aldrig skuffer.',
  ingredients: [
    { text: 'Svineschnitzel 2 stk.', store: 'Aldi', price: '32 kr.', isPantry: false },
    { text: 'Kartofler 600 g', store: 'Aldi', price: '10 kr.', isPantry: false },
    { text: 'Rasp og mel', store: null, price: null, isPantry: true },
    { text: 'Æg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Mayonnaise 3 spsk.', store: null, price: null, isPantry: true },
    { text: 'Purløg hakket', store: null, price: null, isPantry: true },
    { text: 'Smør til stegning', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Bank schnitzlerne flade med en kødhammer. Vend dem i mel, pisket æg og rasp.',
    'Steg dem i generøst smør 3-4 minutter på hver side til gyldne og sprøde.',
    'Kog kartoflerne, afkøl og skær dem i tern.',
    'Bland kartofler med mayonnaise og purløg. Krydr med salt og peber.',
    'Server schnitzlerne varme med kartoffelsalaten og en citronbåd.',
  ],
  tip: 'Tilsæt en klat smør til panden halvvejs igennem stegningen for ekstra gyldne schnitzler.',
  dealItems: [
    { name: 'Svineschnitzel 2 stk.', store: 'Aldi', price: '32 kr.' },
    { name: 'Kartofler 600 g', store: 'Aldi', price: '10 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Hjemmelavet Pizza Margherita',
  emoji: '🍕', time: '40 minutter', servings_count: 2,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En simpel og lækker hjemmelavet pizza med sprød bund, tomatpuré, smeltet mozzarella og frisk basilikum. Bedre end takeaway og klar på 40 minutter. Den enkle version er tit den bedste.',
  ingredients: [
    { text: 'Pizzadej frisk 2 stk.', store: 'Aldi', price: '18 kr.', isPantry: false },
    { text: 'Mozzarella 2x125 g', store: 'Aldi', price: '28 kr.', isPantry: false },
    { text: 'Passata tomatpuré 500 g', store: 'Aldi', price: '12 kr.', isPantry: false },
    { text: 'Frisk basilikum', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 1 fed', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 250°C med pizzastenen eller en bageplade inde.',
    'Bland passata med knust hvidløg, olivenolie, salt og peber.',
    'Rul pizzadejen ud tyndt på bagepapir.',
    'Smør tomatsauce på bunden, fordel revet mozzarella over.',
    'Bag 10-12 minutter til bunden er sprød og osten er gylden og boblende.',
    'Tag ud, top med friske basilikumblade og dryp med olivenolie.',
  ],
  tip: 'Brug altid den varmeste ovn du har – høj varme er nøglen til en sprød pizzabund.',
  dealItems: [
    { name: 'Pizzadej frisk', store: 'Aldi', price: '18 kr.' },
    { name: 'Mozzarella 2x125 g', store: 'Aldi', price: '28 kr.' },
    { name: 'Passata 500 g', store: 'Aldi', price: '12 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Svinekød med Nudler og Woksauce',
  emoji: '🥢', time: '25 minutter', servings_count: 2,
  category: 'Asiatisk', cuisine: '🇯🇵 Asiatisk',
  description: 'Strimlet svinekød wokket med sprøde grøntsager og glasnudler i en smagfuld soja- og hoisinsauce. Hurtig og mættende hverdagsret inspireret af asiatisk street food. Klar på 25 minutter.',
  ingredients: [
    { text: 'Svinekød strimler 300 g', store: 'Aldi', price: '28 kr.', isPantry: false },
    { text: 'Wokgrøntsager pose 400 g', store: 'Aldi', price: '18 kr.', isPantry: false },
    { text: 'Glasnudler 100 g', store: 'Aldi', price: '12 kr.', isPantry: false },
    { text: 'Sojasauce 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Hoisinsauce 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Sesamolie 1 tsk.', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Udblød glasnudlerne i kogende vand 5 minutter og afvand.',
    'Varm en wokpande op til høj varme med lidt olie.',
    'Wok svinekødet 3 minutter ved høj varme. Tilsæt hvidløg og grøntsager og wok 3 minutter mere.',
    'Tilsæt nudler, sojasauce og hoisinsauce. Vend det hele godt.',
    'Sluk for varmen og dryp sesamolie over. Server straks.',
  ],
  tip: 'En varm wok er vigtigere end noget andet – brug højeste varme og arbejd hurtigt.',
  dealItems: [
    { name: 'Svinekød strimler 300 g', store: 'Aldi', price: '28 kr.' },
    { name: 'Wokgrøntsager pose 400 g', store: 'Aldi', price: '18 kr.' },
    { name: 'Glasnudler 100 g', store: 'Aldi', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Bønnesuppe med Skinke og Tomat',
  emoji: '🫒', time: '35 minutter', servings_count: 4,
  category: 'Middelhavet', cuisine: '🇬🇷 Middelhavet',
  description: 'En fyldig og varmende bønnesuppe med røget skinke, hakkede tomater og friske urter. Fuld af protein og fibre og klar på under 35 minutter. En rustik hverdagsret der mætter og varmer.',
  ingredients: [
    { text: 'Hvide bønner 2 dåser', store: 'Aldi', price: '16 kr.', isPantry: false },
    { text: 'Røget skinke 200 g', store: 'Aldi', price: '24 kr.', isPantry: false },
    { text: 'Hakkede tomater 1 dåse', store: 'Aldi', price: '8 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Grøntsagsbouillon 8 dl', store: null, price: null, isPantry: true },
    { text: 'Timian og rosmarin', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær skinken i tern og brun den i en gryde. Tag den op.',
    'Svits løg og hvidløg i fedtet 3 minutter.',
    'Tilsæt tomater, bønner, bouillon og urter. Kog op og lad det simre 20 minutter.',
    'Tilsæt skinken tilbage. Smag til med salt og peber.',
    'Server med ristet brød og evt. revet parmesan.',
  ],
  tip: 'Blend en tredjedel af suppen og rør det i igen for en cremet konsistens uden at miste teksturen.',
  dealItems: [
    { name: 'Hvide bønner 2 dåser', store: 'Aldi', price: '16 kr.' },
    { name: 'Røget skinke 200 g', store: 'Aldi', price: '24 kr.' },
    { name: 'Hakkede tomater', store: 'Aldi', price: '8 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Hakkebøf med Stegte Løg og Bagt Kartoffel',
  emoji: '🌿', time: '40 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Klassisk dansk hakkebøf med en skov af søde stegte løg og en sprød bagt kartoffel med creme fraiche. En simpel ret der aldrig går af mode og altid smager godt. Server med et glas kold mælk.',
  ingredients: [
    { text: 'Hakket oksekød 400 g', store: 'Aldi', price: '30 kr.', isPantry: false },
    { text: 'Løg 3 store', store: 'Aldi', price: '8 kr.', isPantry: false },
    { text: 'Bagekartofler 2 store', store: 'Aldi', price: '12 kr.', isPantry: false },
    { text: 'Creme fraiche', store: null, price: null, isPantry: true },
    { text: 'Smør', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 200°C. Gnid kartoflerne med olie og salt og bag dem 40-45 minutter.',
    'Form oksekødet til 2 bøffer og krydr med salt og peber.',
    'Skær løgene i ringe og steg dem i smør på lav varme 20 minutter til gyldne og bløde.',
    'Steg hakkebøfferne på en varm pande 4-5 minutter på hver side.',
    'Server bøfferne med stegte løg på toppen og bagekartoflen med creme fraiche ved siden af.',
  ],
  tip: 'Tilsæt lidt sukker til løgene de sidste 5 minutter for ekstra sødme og glans.',
  dealItems: [
    { name: 'Hakket oksekød 400 g', store: 'Aldi', price: '30 kr.' },
    { name: 'Løg 3 store', store: 'Aldi', price: '8 kr.' },
    { name: 'Bagekartofler 2 stk.', store: 'Aldi', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Pitabrød med Tzatziki og Grillede Grøntsager',
  emoji: '🫒', time: '25 minutter', servings_count: 2,
  category: 'Middelhavet', cuisine: '🇬🇷 Middelhavet',
  description: 'Lune pitabrød fyldt med cremet hjemmelavet tzatziki og saftige grillede grøntsager. En lækker og mættende vegetarisk ret inspireret af Middelhavets køkken. Perfekt til en let aftensmad eller frokost.',
  ingredients: [
    { text: 'Pitabrød 4 stk.', store: 'Aldi', price: '14 kr.', isPantry: false },
    { text: 'Græsk yoghurt 300 g', store: 'Aldi', price: '16 kr.', isPantry: false },
    { text: 'Agurk 1 stk.', store: 'Aldi', price: '8 kr.', isPantry: false },
    { text: 'Peberfrugt 2 stk.', store: 'Aldi', price: '16 kr.', isPantry: false },
    { text: 'Zucchini 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Dild og salt', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Riv agurken groft, klem al væde ud. Bland med yoghurt, hvidløg, dild og salt – det er tzatzikien.',
    'Skær peberfrugter og zucchini i strimler. Grill dem i olivenolie 5-6 minutter på en grillpande.',
    'Varm pitabrødene i ovnen eller en tør pande.',
    'Skær pitaen op og fyld med tzatziki og grillede grøntsager.',
  ],
  tip: 'Lad tzatzikien trække i køleskabet mindst 30 minutter – den smager meget bedre næste dag.',
  dealItems: [
    { name: 'Pitabrød 4 stk.', store: 'Aldi', price: '14 kr.' },
    { name: 'Græsk yoghurt 300 g', store: 'Aldi', price: '16 kr.' },
    { name: 'Agurk 1 stk.', store: 'Aldi', price: '8 kr.' },
    { name: 'Peberfrugt 2 stk.', store: 'Aldi', price: '16 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Fiskefrikadeller med Remoulade og Salat',
  emoji: '🐟', time: '30 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Hjemmelavede fiskefrikadeller af frisk torsk med purløg og citronskal serveret med klassisk remoulade og frisk salat. En dansk klassiker der smager af sommer og hav. Både til frokost og aftensmad.',
  ingredients: [
    { text: 'Torskefilet 500 g', store: 'Aldi', price: '44 kr.', isPantry: false },
    { text: 'Remoulade 1 glas', store: 'Aldi', price: '16 kr.', isPantry: false },
    { text: 'Rugbrød til servering', store: 'Aldi', price: '18 kr.', isPantry: false },
    { text: 'Æg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Mel 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Purløg hakket', store: null, price: null, isPantry: true },
    { text: 'Citronskal', store: null, price: null, isPantry: true },
    { text: 'Smør til stegning', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Hak torsken fint med en kniv eller i en foodprocessor.',
    'Bland fisk med æg, mel, purløg og citronskal. Krydr med salt og peber.',
    'Form frikadeller med en ske og steg dem i smør 3-4 minutter på hver side til gyldne.',
    'Server på rugbrød med remoulade og frisk salat.',
  ],
  tip: 'Hvis farsen er for løs kan du tilsætte lidt ekstra mel eller sætte den i køleskabet 15 minutter.',
  dealItems: [
    { name: 'Torskefilet 500 g', store: 'Aldi', price: '44 kr.' },
    { name: 'Remoulade', store: 'Aldi', price: '16 kr.' },
    { name: 'Rugbrød', store: 'Aldi', price: '18 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Ungarsk Gulasch med Kartofler',
  emoji: '🌿', time: '70 minutter', servings_count: 4,
  category: 'Europæisk', cuisine: '🇩🇰 Nordisk',
  description: 'En rig og krydret ungarsk gulasch med mørt oksekød, masser af paprika og kartofler. En ret der simrer sig til perfektion og fylder hele køkkenet med vidunderlig duft. Server med surt og rugbrød.',
  ingredients: [
    { text: 'Oksekød grydesteg 600 g', store: 'Aldi', price: '60 kr.', isPantry: false },
    { text: 'Kartofler 800 g', store: 'Aldi', price: '12 kr.', isPantry: false },
    { text: 'Peberfrugt 2 stk.', store: 'Aldi', price: '16 kr.', isPantry: false },
    { text: 'Løg 2 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Paprika røget og sød i alt 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Tomatpuré 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Oksebouillon 6 dl', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær kødet i tern og brun det i portioner i olie. Tag det op.',
    'Svits løg, hvidløg og peberfrugter 5 minutter. Tilsæt paprika og tomatpuré, rør 1 minut.',
    'Læg kødet tilbage, tilsæt bouillon. Simr med låg 40 minutter.',
    'Tilsæt kartofler i tern og kog videre 20 minutter til alt er mørt.',
    'Smag til og server med creme fraiche og rugbrød.',
  ],
  tip: 'Paprika er stjerneingrediensen – brug god kvalitet og vær generøs. Det giver suppen dens karakteristiske dybe farve og smag.',
  dealItems: [
    { name: 'Oksekød grydesteg 600 g', store: 'Aldi', price: '60 kr.' },
    { name: 'Kartofler 800 g', store: 'Aldi', price: '12 kr.' },
    { name: 'Peberfrugt 2 stk.', store: 'Aldi', price: '16 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Pandekager med Syltetøj og Vaniljecreme',
  emoji: '🌿', time: '30 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Tynde og luftige pandekager serveret med sødt jordbærsyltetøj og en blød vaniljefromage. En elsket klassiker til dessert eller som søndagsfrokost for hele familien. Nem at lave og kæmpe hit hos børnene.',
  ingredients: [
    { text: 'Æg 3 stk.', store: 'Aldi', price: '10 kr.', isPantry: false },
    { text: 'Mælk 4 dl', store: 'Aldi', price: '8 kr.', isPantry: false },
    { text: 'Jordbærsyltetøj 1 glas', store: 'Aldi', price: '18 kr.', isPantry: false },
    { text: 'Mel 150 g', store: null, price: null, isPantry: true },
    { text: 'Smør til stegning', store: null, price: null, isPantry: true },
    { text: 'Vaniljesukker 1 tsk.', store: null, price: null, isPantry: true },
    { text: 'Flormelis til drys', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Pisk æg, mælk, mel og vaniljesukker til en glat dej. Lad den hvile 10 minutter.',
    'Smelt en lille smørklat i en pande ved middel-høj varme.',
    'Hæld et tyndt lag dej i panden og steg 1-2 minutter til undersiden er gylden. Vend og steg 1 minut mere.',
    'Gentag til al dejen er brugt – du får ca. 10-12 pandekager.',
    'Server med syltetøj, flormelis og evt. vaniljefromage.',
  ],
  tip: 'Den første pandekage er altid et testeksemplar – brug den til at justere varmen og smørklattens størrelse.',
  dealItems: [
    { name: 'Æg 3 stk.', store: 'Aldi', price: '10 kr.' },
    { name: 'Mælk 4 dl', store: 'Aldi', price: '8 kr.' },
    { name: 'Jordbærsyltetøj', store: 'Aldi', price: '18 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Æggekage med Bacon og Forårsløg',
  emoji: '🌿', time: '20 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En klassisk dansk æggekage med sprødt bacon, friske forårsløg og et drys chili. Enkel og mættende – perfekt til en hurtig aftensmad med rugbrød ved siden af. En ret danskerne har elsket i generationer.',
  ingredients: [
    { text: 'Æg 6 stk.', store: 'Aldi', price: '14 kr.', isPantry: false },
    { text: 'Bacon 150 g', store: 'Aldi', price: '20 kr.', isPantry: false },
    { text: 'Forårsløg 1 bundt', store: 'Aldi', price: '10 kr.', isPantry: false },
    { text: 'Mælk 3 spsk.', store: null, price: null, isPantry: true },
    { text: 'Smør', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Steg bacon i en pande til sprødt. Tag bacon op, lad fedtet blive i panden.',
    'Pisk æg og mælk sammen. Krydr med salt og peber.',
    'Hæld æggeblandingen i panden med baconfedtet ved middel varme.',
    'Lad æggekagen sætte sig uden at røre – ca. 5-6 minutter til den er fast men stadig let cremet i midten.',
    'Top med bacon og snittede forårsløg. Server med rugbrød.',
  ],
  tip: 'Rør aldrig i æggekagen – lad den sætte sig langsomt for den cremede konsistens.',
  dealItems: [
    { name: 'Æg 6 stk.', store: 'Aldi', price: '14 kr.' },
    { name: 'Bacon 150 g', store: 'Aldi', price: '20 kr.' },
    { name: 'Forårsløg 1 bundt', store: 'Aldi', price: '10 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},

// ── COOP-GRUPPE MULTI ─────────────────────────────────────────────────────
// Covers: Spar, Eurospar, Meny, SuperBrugsen/Kvickly, Dagli'Brugsen / Brugsen
{
  id: id(), title: 'Kyllingesteg med Estragon og Flødesauce',
  emoji: '🌿', time: '60 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En saftig kyllingesteg med en elegant estragonbaseret flødesauce og dampede kartofler. En klassisk søndag i en lidt finere udgave. Kyllingen passer sig selv i ovnen mens du laver saucen.',
  ingredients: [
    { text: 'Hel kylling 1,4 kg', store: 'Meny', price: '69 kr.', isPantry: false },
    { text: 'Kartofler 1 kg', store: 'Spar', price: '12 kr.', isPantry: false },
    { text: 'Piskefløde 2 dl', store: 'Eurospar', price: '14 kr.', isPantry: false },
    { text: 'Estragon frisk', store: "SuperBrugsen / Kvickly", price: '12 kr.', isPantry: false },
    { text: 'Hvidvin tør 1 dl', store: "Dagli'Brugsen / Brugsen", price: '18 kr.', isPantry: false },
    { text: 'Smør og olivenolie', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 4 fed', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 190°C. Gnid kyllingen med smør, salt og peber indvendig og udvendig.',
    'Fyld kyllingen med halvt estragon og hele hvidløgsfed. Bag 50-60 minutter.',
    'Kog stegeskyen op med hvidvin og lad den reducere halvt. Tilsæt fløde og resten af estragonen.',
    'Lad saucen simre 5 minutter til den er cremet. Smag til.',
    'Kog kartoflerne og server med kyllingen og saucen.',
  ],
  tip: 'Hvil kyllingen tildækket i 10 minutter inden udskæring – saften fordeler sig og kødet bliver saftigere.',
  dealItems: [
    { name: 'Hel kylling 1,4 kg', store: 'Meny', price: '69 kr.' },
    { name: 'Kartofler 1 kg', store: 'Spar', price: '12 kr.' },
    { name: 'Piskefløde 2 dl', store: 'Eurospar', price: '14 kr.' },
    { name: 'Estragon frisk', store: 'SuperBrugsen / Kvickly', price: '12 kr.' },
    { name: 'Hvidvin tør 1 dl', store: "Dagli'Brugsen / Brugsen", price: '18 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Oksesteg med Rødvinssauce og Ovnbagte Rodfrugter',
  emoji: '🌿', time: '80 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En festlig oksesteg med en dyb rødvinssauce og karamelliserede ovnbagte rodfrugter. Perfekt til en lørdag hvor der er tid til at lave noget ordentligt. Imponerende resultat med overraskende lidt arbejde.',
  ingredients: [
    { text: 'Okseculotte 1 kg', store: 'Meny', price: '89 kr.', isPantry: false },
    { text: 'Gulerødder 4 stk.', store: 'Spar', price: '8 kr.', isPantry: false },
    { text: 'Pastinakker 2 stk.', store: "Dagli'Brugsen / Brugsen", price: '12 kr.', isPantry: false },
    { text: 'Rødvin 2 dl', store: 'Eurospar', price: '20 kr.', isPantry: false },
    { text: 'Rødbeder 3 stk.', store: 'SuperBrugsen / Kvickly', price: '14 kr.', isPantry: false },
    { text: 'Oksefond 4 dl', store: null, price: null, isPantry: true },
    { text: 'Timian og laurbær', store: null, price: null, isPantry: true },
    { text: 'Smør og olivenolie', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 160°C. Brun stegen på alle sider i smør i en gryde.',
    'Læg stegen i et fad med timian og laurbær. Bag 60-70 minutter til kernetemp 58°C (rosa).',
    'Skær rodfrugterne groft og bag dem ved 200°C i 35 minutter til karamelliserede.',
    'Kog stegeskyen op med rødvin og fond. Reducer til en glansfuld sauce, si den og smag til.',
    'Hvil stegen 15 minutter inden udskæring. Server med rodfrugter og sauce.',
  ],
  tip: 'Brug et stegetermometer – det er den eneste sikre måde at ramme den rigtige stegegrad.',
  dealItems: [
    { name: 'Okseculotte 1 kg', store: 'Meny', price: '89 kr.' },
    { name: 'Gulerødder 4 stk.', store: 'Spar', price: '8 kr.' },
    { name: 'Pastinakker 2 stk.', store: "Dagli'Brugsen / Brugsen", price: '12 kr.' },
    { name: 'Rødvin 2 dl', store: 'Eurospar', price: '20 kr.' },
    { name: 'Rødbeder 3 stk.', store: 'SuperBrugsen / Kvickly', price: '14 kr.' },
  ],
  dietaryFilters: [], difficulty: 'mellem',
},
{
  id: id(), title: 'Pasta Bolognese med Grøntsager og Oksekød',
  emoji: '🍝', time: '45 minutter', servings_count: 4,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En rig og kødsauce til spaghetti med hakket oksekød, soffritto af grøntsager og masser af tomat. Den ultimate trøstemad der giver et dejligt overskud til frysen. Simrer sig til en dyb og afrundet smag.',
  ingredients: [
    { text: 'Hakket oksekød 500 g', store: 'Meny', price: '48 kr.', isPantry: false },
    { text: 'Spaghetti 400 g', store: 'Spar', price: '16 kr.', isPantry: false },
    { text: 'Hakkede tomater 2 dåser', store: 'Eurospar', price: '18 kr.', isPantry: false },
    { text: 'Gulerødder 2 stk.', store: 'SuperBrugsen / Kvickly', price: '6 kr.', isPantry: false },
    { text: 'Selleri 2 stængler', store: "Dagli'Brugsen / Brugsen", price: '8 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Tomatpuré 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Hak løg, gulerødder og selleri fint og svits dem i olivenolie 8 minutter.',
    'Tilsæt hvidløg og tomatpuré. Steg 2 minutter.',
    'Tilsæt oksekødet og brun det godt.',
    'Hæld tomater i og lad saucen simre 30 minutter. Smag til.',
    'Kog spaghetti og server med bolognesen og parmesan.',
  ],
  tip: 'Jo længere saucen simrer, desto bedre smager den. 2 timer giver den dybeste smag.',
  dealItems: [
    { name: 'Hakket oksekød 500 g', store: 'Meny', price: '48 kr.' },
    { name: 'Spaghetti 400 g', store: 'Spar', price: '16 kr.' },
    { name: 'Hakkede tomater 2 dåser', store: 'Eurospar', price: '18 kr.' },
    { name: 'Gulerødder 2 stk.', store: 'SuperBrugsen / Kvickly', price: '6 kr.' },
    { name: 'Selleri 2 stængler', store: "Dagli'Brugsen / Brugsen", price: '8 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Laks med Couscous og Ristede Grøntsager',
  emoji: '🐟', time: '30 minutter', servings_count: 2,
  category: 'Middelhavet', cuisine: '🇬🇷 Middelhavet',
  description: 'Ovnbagt laks med luftig couscous og en farverig blanding af ristede grøntsager med harissa. En let og nærende ret med masser af smag og kun ét fad at vaske op. Perfekt til en sund hverdagsaften.',
  ingredients: [
    { text: 'Laks 2 fileter 300 g', store: 'Meny', price: '52 kr.', isPantry: false },
    { text: 'Couscous 200 g', store: 'Eurospar', price: '14 kr.', isPantry: false },
    { text: 'Squash 1 stk.', store: 'Spar', price: '12 kr.', isPantry: false },
    { text: 'Cherrytomater 200 g', store: "Dagli'Brugsen / Brugsen", price: '16 kr.', isPantry: false },
    { text: 'Rødløg 1 stk.', store: 'SuperBrugsen / Kvickly', price: '6 kr.', isPantry: false },
    { text: 'Harissa 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 200°C.',
    'Skær squash og rødløg i tern. Bland med cherrytomater, harissa og olivenolie. Bag 20 minutter.',
    'Krydr laksen og læg den på grøntsagerne de sidste 12 minutter.',
    'Hæld kogende vand over couscousen (1:1,5 ratio). Lad den stå tildækket 5 minutter, fluff med en gaffel.',
    'Server laks og grøntsager over couscous.',
  ],
  tip: 'Tilsæt en nip sukker til harissa-grøntsagerne – det balancerer krydderiet og fremhæver sødmen i tomaterne.',
  dealItems: [
    { name: 'Laks 2 fileter', store: 'Meny', price: '52 kr.' },
    { name: 'Couscous 200 g', store: 'Eurospar', price: '14 kr.' },
    { name: 'Squash 1 stk.', store: 'Spar', price: '12 kr.' },
    { name: 'Cherrytomater 200 g', store: "Dagli'Brugsen / Brugsen", price: '16 kr.' },
    { name: 'Rødløg 1 stk.', store: 'SuperBrugsen / Kvickly', price: '6 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Spaghetti med Rejer og Hvidvinssauce',
  emoji: '🍝', time: '25 minutter', servings_count: 2,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En elegant spaghetti med saftige rejer i en let hvidvinssauce med hvidløg og persille. En ret der smager af restaurant men er klar på 25 minutter. Perfekt til en romantisk middag for to.',
  ingredients: [
    { text: 'Rejer pillede 250 g', store: 'Meny', price: '45 kr.', isPantry: false },
    { text: 'Spaghetti 250 g', store: 'Spar', price: '12 kr.', isPantry: false },
    { text: 'Hvidvin tør 1 dl', store: 'Eurospar', price: '16 kr.', isPantry: false },
    { text: 'Cherrytomater 150 g', store: "Dagli'Brugsen / Brugsen", price: '12 kr.', isPantry: false },
    { text: 'Persille frisk', store: 'SuperBrugsen / Kvickly', price: '8 kr.', isPantry: false },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Chiliflager', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Kog spaghetti al dente. Gem 1 dl pastavand.',
    'Svits hvidløg og chiliflager i olivenolie 1 minut.',
    'Tilsæt rejer og steg 2 minutter. Tag dem op.',
    'Deglaser panden med hvidvin, tilsæt cherrytomater og kog 3 minutter.',
    'Vend pasta i saucen med lidt pastavand. Tilsæt rejer og persille. Server straks.',
  ],
  tip: 'Undgå at overstege rejerne – 2 minutter er nok. De fortsætter med at tilberede sig af den varme sauce.',
  dealItems: [
    { name: 'Rejer pillede 250 g', store: 'Meny', price: '45 kr.' },
    { name: 'Spaghetti 250 g', store: 'Spar', price: '12 kr.' },
    { name: 'Hvidvin tør 1 dl', store: 'Eurospar', price: '16 kr.' },
    { name: 'Cherrytomater 150 g', store: "Dagli'Brugsen / Brugsen", price: '12 kr.' },
    { name: 'Persille frisk', store: 'SuperBrugsen / Kvickly', price: '8 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Svamperisotto med Parmesan og Hvidvin',
  emoji: '🍄', time: '40 minutter', servings_count: 2,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En cremet og aromatisk risotto med blandede svampe, hvidvin og masser af parmesan. En vegetarisk ret der kræver opmærksomhed men belønner dig med en udsøgt smag. Perfekt til en stille aften.',
  ingredients: [
    { text: 'Blandede svampe 300 g', store: 'Meny', price: '38 kr.', isPantry: false },
    { text: 'Risottoris 200 g', store: 'Eurospar', price: '20 kr.', isPantry: false },
    { text: 'Parmesan 60 g', store: 'SuperBrugsen / Kvickly', price: '28 kr.', isPantry: false },
    { text: 'Hvidvin tør 1 dl', store: "Dagli'Brugsen / Brugsen", price: '16 kr.', isPantry: false },
    { text: 'Frisk timian', store: 'Spar', price: '10 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Grøntsagsbouillon varm 8 dl', store: null, price: null, isPantry: true },
    { text: 'Smør og olivenolie', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Steg svampene i smør med timian til de er gyldne. Stil til side.',
    'Svits løg og hvidløg i olivenolie 3 minutter. Tilsæt ris og rør 1 minut.',
    'Tilsæt hvidvin og rør til det er absorberet.',
    'Tilsæt varm bouillon én slev ad gangen under konstant omrøring – ca. 20 minutter i alt.',
    'Rør revet parmesan og smør i. Top med svampene. Server straks.',
  ],
  tip: 'Bouillonen skal altid være varm – tilsæt aldrig kold bouillon, da det stopper kogeprocessen og giver klæbrig risotto.',
  dealItems: [
    { name: 'Blandede svampe 300 g', store: 'Meny', price: '38 kr.' },
    { name: 'Risottoris 200 g', store: 'Eurospar', price: '20 kr.' },
    { name: 'Parmesan 60 g', store: 'SuperBrugsen / Kvickly', price: '28 kr.' },
    { name: 'Hvidvin tør 1 dl', store: "Dagli'Brugsen / Brugsen", price: '16 kr.' },
    { name: 'Frisk timian', store: 'Spar', price: '10 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'mellem',
},
{
  id: id(), title: 'Grillet Kylling med Tabbouleh og Hummus',
  emoji: '🫒', time: '30 minutter', servings_count: 2,
  category: 'Mellemøstlig', cuisine: '🇲🇦 Mellemøstlig',
  description: 'Saftigt grillet kyllingebryst marineret i citroner og krydderier serveret med frisk tabbouleh af bulgur og urter og cremet hummus. En lys og frisk ret der er mætter godt uden at virke tung.',
  ingredients: [
    { text: 'Kyllingebryst 2 stk.', store: 'Meny', price: '42 kr.', isPantry: false },
    { text: 'Bulgur 150 g', store: 'Eurospar', price: '16 kr.', isPantry: false },
    { text: 'Hummus 200 g', store: 'SuperBrugsen / Kvickly', price: '22 kr.', isPantry: false },
    { text: 'Frisk persille og mynte', store: "Dagli'Brugsen / Brugsen", price: '14 kr.', isPantry: false },
    { text: 'Cherrytomater 150 g', store: 'Spar', price: '12 kr.', isPantry: false },
    { text: 'Citron 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Spidskommen, paprika, salt', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Mariner kyllingen i olivenolie, citronsaft, spidskommen og paprika 15 minutter.',
    'Hæld kogende vand over bulguren (1:1,5 ratio). Lad stå tildækket 10 minutter, fluff med gaffel.',
    'Bland bulgur med hakket persille, mynte, cherrytomater og citronsaft. Det er tabbouleh.',
    'Grill kyllingen 5-6 minutter på hver side til gennemstegt.',
    'Server kyllingen med tabbouleh og hummus ved siden af.',
  ],
  tip: 'Lad tabboulehen trække 15 minutter inden servering – bulguren suger al smagen op fra urterne.',
  dealItems: [
    { name: 'Kyllingebryst 2 stk.', store: 'Meny', price: '42 kr.' },
    { name: 'Bulgur 150 g', store: 'Eurospar', price: '16 kr.' },
    { name: 'Hummus 200 g', store: 'SuperBrugsen / Kvickly', price: '22 kr.' },
    { name: 'Frisk persille og mynte', store: "Dagli'Brugsen / Brugsen", price: '14 kr.' },
    { name: 'Cherrytomater 150 g', store: 'Spar', price: '12 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Indisk Dal med Naan og Raita',
  emoji: '🍛', time: '35 minutter', servings_count: 4,
  category: 'Indisk', cuisine: '🇮🇳 Indisk',
  description: 'En varmende og proteinrig indisk linsesuppe med krydderier, kokosmælk og tomat serveret med bløde naan og frisk raita. En komplet vegetarisk middag der mætter og varmer på alle de rigtige steder.',
  ingredients: [
    { text: 'Røde linser 300 g', store: 'Eurospar', price: '18 kr.', isPantry: false },
    { text: 'Naan brød 4 stk.', store: 'Meny', price: '24 kr.', isPantry: false },
    { text: 'Kokosmælk 400 ml', store: 'SuperBrugsen / Kvickly', price: '22 kr.', isPantry: false },
    { text: 'Græsk yoghurt 200 g', store: "Dagli'Brugsen / Brugsen", price: '16 kr.', isPantry: false },
    { text: 'Frisk koriander', store: 'Spar', price: '10 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg og ingefær', store: null, price: null, isPantry: true },
    { text: 'Hakkede tomater halvdåse', store: null, price: null, isPantry: true },
    { text: 'Karry, gurkemeje, garam masala', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Svits løg, hvidløg og ingefær 5 minutter. Tilsæt krydderier og rør 1 minut.',
    'Tilsæt linser, tomater og kokosmælk. Kog op og simr 25 minutter til linserne er møre.',
    'Lav raita: bland yoghurt med hakket koriander, salt og et nip spidskommen.',
    'Varm naanbrødene i ovnen 3 minutter.',
    'Server dallen med naanbrød og raita ved siden af.',
  ],
  tip: 'Tilsæt en klat smør lige inden servering for ekstra rigdom – det er den indiske hemmelighed der hedder "tarka".',
  dealItems: [
    { name: 'Røde linser 300 g', store: 'Eurospar', price: '18 kr.' },
    { name: 'Naan brød 4 stk.', store: 'Meny', price: '24 kr.' },
    { name: 'Kokosmælk 400 ml', store: 'SuperBrugsen / Kvickly', price: '22 kr.' },
    { name: 'Græsk yoghurt 200 g', store: "Dagli'Brugsen / Brugsen", price: '16 kr.' },
    { name: 'Frisk koriander', store: 'Spar', price: '10 kr.' },
  ],
  dietaryFilters: ['Vegetar', 'Vegansk'], difficulty: 'nem',
},
{
  id: id(), title: 'Fiskefilet med Bagte Kartofler og Tartarsauce',
  emoji: '🐟', time: '40 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Paneret og sprød fiskefilet serveret med bagte kartofler og en cremet hjemmelavet tartarsauce. En klassisk ret der giver god mening på alle fronter – billig, nem og velsmagende.',
  ingredients: [
    { text: 'Paneret fiskefilet 4 stk.', store: 'Meny', price: '42 kr.', isPantry: false },
    { text: 'Bagekartofler 2 stk.', store: 'Spar', price: '12 kr.', isPantry: false },
    { text: 'Creme fraiche 38% 200 g', store: 'Eurospar', price: '18 kr.', isPantry: false },
    { text: 'Kapers 1 spsk.', store: 'SuperBrugsen / Kvickly', price: '14 kr.', isPantry: false },
    { text: 'Agurker syltede 2 spsk.', store: "Dagli'Brugsen / Brugsen", price: '10 kr.', isPantry: false },
    { text: 'Dijonsennep 1 tsk.', store: null, price: null, isPantry: true },
    { text: 'Purløg hakket', store: null, price: null, isPantry: true },
    { text: 'Olivenolie og salt', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 200°C. Gnid kartoflerne med olie og salt og bag 40-45 minutter.',
    'Lav tartarsauce: bland creme fraiche med kapers, syltede agurker, sennep og purløg. Smag til.',
    'Bag fiskefileterne efter pakkens anvisning eller steg dem i smør 4 minutter på hver side.',
    'Server fisken med de bagte kartofler og tartarsauce.',
  ],
  tip: 'Lav tartarsaucen i god tid og lad den trække i køleskabet – smagen udvikler sig og bliver bedre.',
  dealItems: [
    { name: 'Paneret fiskefilet', store: 'Meny', price: '42 kr.' },
    { name: 'Bagekartofler 2 stk.', store: 'Spar', price: '12 kr.' },
    { name: 'Creme fraiche 200 g', store: 'Eurospar', price: '18 kr.' },
    { name: 'Kapers', store: 'SuperBrugsen / Kvickly', price: '14 kr.' },
    { name: 'Syltede agurker', store: "Dagli'Brugsen / Brugsen", price: '10 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Vegetarisk Lasagne med Spinat og Ricotta',
  emoji: '🍝', time: '60 minutter', servings_count: 4,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En cremet og tilfredsstillende vegetarisk lasagne med lag af spinat, ricotta og tomatsugo. Ovnbagt til perfektion med smeltet ost på toppen. En klassiker der passer til alle og altid imponerer ved middagsbordet.',
  ingredients: [
    { text: 'Ricotta 500 g', store: 'Meny', price: '36 kr.', isPantry: false },
    { text: 'Lasagneplader 250 g', store: 'Spar', price: '16 kr.', isPantry: false },
    { text: 'Frossen spinat 400 g', store: 'Eurospar', price: '18 kr.', isPantry: false },
    { text: 'Hakkede tomater 2 dåser', store: 'SuperBrugsen / Kvickly', price: '16 kr.', isPantry: false },
    { text: 'Revet ost 200 g', store: "Dagli'Brugsen / Brugsen", price: '28 kr.', isPantry: false },
    { text: 'Løg og hvidløg', store: null, price: null, isPantry: true },
    { text: 'Muskatnød og oregano', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Forvarm ovnen til 180°C.',
    'Lav tomatsauce: svits løg og hvidløg, tilsæt tomater og oregano, simr 15 minutter.',
    'Optø og pres spinaten for vand. Bland med ricotta, muskatnød, salt og peber.',
    'Byg lasagnen: tomatsauce, plader, ricoitablanding, gentag. Afslut med tomatsauce og revet ost.',
    'Bag 35-40 minutter til toppen er gylden og boblende.',
  ],
  tip: 'Lad lasagnen hvile 10 minutter inden udskæring – den sætter sig og er nemmere at portionere.',
  dealItems: [
    { name: 'Ricotta 500 g', store: 'Meny', price: '36 kr.' },
    { name: 'Lasagneplader 250 g', store: 'Spar', price: '16 kr.' },
    { name: 'Frossen spinat 400 g', store: 'Eurospar', price: '18 kr.' },
    { name: 'Hakkede tomater 2 dåser', store: 'SuperBrugsen / Kvickly', price: '16 kr.' },
    { name: 'Revet ost 200 g', store: "Dagli'Brugsen / Brugsen", price: '28 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},

// ── FAKTA + IRMA (10 recipes, each covering both chains) ──────────────────
{
  id: id(), title: 'Cremede Svampe på Ristet Brød',
  emoji: '🍄', time: '20 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Gyldne svampe sauteret med hvidløg, timian og fløde serveret på sprødt ristet surdejsbrød. En udsøgt og hurtig ret der kan bruges som forret, frokost eller let aftensmad.',
  ingredients: [
    { text: 'Blandede svampe 400 g', store: 'Fakta', price: '28 kr.', isPantry: false },
    { text: 'Surdejsbrød 4 skiver', store: 'Irma', price: '22 kr.', isPantry: false },
    { text: 'Piskefløde 1 dl', store: 'Fakta', price: '12 kr.', isPantry: false },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Frisk timian', store: null, price: null, isPantry: true },
    { text: 'Smør', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær svampene i skiver og steg dem i smør ved høj varme til de er gyldne. Krydr med salt.',
    'Skru ned, tilsæt hvidløg og timian og steg 1 minut.',
    'Tilsæt fløden og lad den reducere 2-3 minutter til cremet.',
    'Rist brødskiverne. Top med svampeblandingen og drys med frisk timian.',
  ],
  tip: 'Overfyld aldrig panden med svampe – steg dem i portioner for at få den gyldne stegeskorpe.',
  dealItems: [
    { name: 'Blandede svampe 400 g', store: 'Fakta', price: '28 kr.' },
    { name: 'Surdejsbrød', store: 'Irma', price: '22 kr.' },
    { name: 'Piskefløde 1 dl', store: 'Fakta', price: '12 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Røget Pølse med Sauerkraut og Sennep',
  emoji: '🌿', time: '20 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Klassisk dansk pølsemad med røget svinepølse, syrlig sauerkraut og stærk sennep. En hurtig og billig hverdagsret der smager langt bedre end den ser ud. Klar på 20 minutter.',
  ingredients: [
    { text: 'Røget svinepølse 400 g', store: 'Fakta', price: '26 kr.', isPantry: false },
    { text: 'Sauerkraut 1 glas', store: 'Irma', price: '18 kr.', isPantry: false },
    { text: 'Kartofler 600 g', store: 'Fakta', price: '10 kr.', isPantry: false },
    { text: 'Grov sennep', store: null, price: null, isPantry: true },
    { text: 'Smør', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Kog kartoflerne møre i saltet vand, ca. 20 minutter.',
    'Varm sauerkrauten i en lille gryde ved lav varme.',
    'Skær pølsen i skiver og steg dem i smør 3-4 minutter til let sprøde.',
    'Server pølse og sauerkraut med kartofler og grov sennep.',
  ],
  tip: 'Tilsæt lidt æblecidereddike til sauerkrauten under opvarmning for ekstra syre og friskhed.',
  dealItems: [
    { name: 'Røget svinepølse 400 g', store: 'Fakta', price: '26 kr.' },
    { name: 'Sauerkraut', store: 'Irma', price: '18 kr.' },
    { name: 'Kartofler 600 g', store: 'Fakta', price: '10 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Kyllingewok med Broccoli og Sojasauce',
  emoji: '🥢', time: '20 minutter', servings_count: 2,
  category: 'Asiatisk', cuisine: '🇯🇵 Asiatisk',
  description: 'Sprødt wokket kyllingebryst med broccoli, forårsløg og en smagfuld soja- og ingefærsauce. Hurtig, sund og mættende. Server med dampet jasminris for en komplet middag på hverdagsaftener.',
  ingredients: [
    { text: 'Kyllingebryst 300 g', store: 'Fakta', price: '36 kr.', isPantry: false },
    { text: 'Broccoli 1 hoved', store: 'Irma', price: '18 kr.', isPantry: false },
    { text: 'Jasminris 200 g', store: 'Fakta', price: '14 kr.', isPantry: false },
    { text: 'Sojasauce 3 spsk.', store: null, price: null, isPantry: true },
    { text: 'Ingefær frisk 1 tsk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Sesamolie', store: null, price: null, isPantry: true },
    { text: 'Forårsløg til pynt', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Kog risen efter pakkens anvisning.',
    'Skær kyllingen i strimler. Wok den ved høj varme 4 minutter til gylden.',
    'Tilsæt broccoli i buketter og wok 3 minutter.',
    'Tilsæt hvidløg, ingefær og sojasauce. Vend det hele godt og wok 1 minut mere.',
    'Sluk varmen, dryp sesamolie over og top med snittede forårsløg. Server med ris.',
  ],
  tip: 'Skær kyllingen på tværs af kødfibrene – det giver møre strimler der tilberedes jævnt.',
  dealItems: [
    { name: 'Kyllingebryst 300 g', store: 'Fakta', price: '36 kr.' },
    { name: 'Broccoli 1 hoved', store: 'Irma', price: '18 kr.' },
    { name: 'Jasminris 200 g', store: 'Fakta', price: '14 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Linsebolognese med Fuldkornspasta',
  emoji: '🍝', time: '35 minutter', servings_count: 4,
  category: 'Italiensk', cuisine: '🇮🇹 Italiensk',
  description: 'En plantebaseret bolognese lavet på grønne linser og masser af grøntsager i en rig tomatsauce. Fuld af smag og protein og du savner slet ikke kødet. Server med fuldkornspasta for ekstra næring.',
  ingredients: [
    { text: 'Grønne linser 250 g', store: 'Irma', price: '22 kr.', isPantry: false },
    { text: 'Fuldkornspasta 400 g', store: 'Fakta', price: '18 kr.', isPantry: false },
    { text: 'Hakkede tomater 2 dåser', store: 'Irma', price: '18 kr.', isPantry: false },
    { text: 'Gulerødder 2 stk.', store: null, price: null, isPantry: true },
    { text: 'Selleri 2 stængler', store: null, price: null, isPantry: true },
    { text: 'Løg og hvidløg', store: null, price: null, isPantry: true },
    { text: 'Tomatpuré og oregano', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skyl linserne. Svits finthakket løg, gulerødder og selleri 8 minutter.',
    'Tilsæt hvidløg og tomatpuré, steg 2 minutter.',
    'Tilsæt linser, tomater og 3 dl vand. Simr 25 minutter til linserne er møre og saucen tyknet.',
    'Krydr med oregano, salt og peber.',
    'Kog pasta og server med saucen og et drys parmesan.',
  ],
  tip: 'Tilsæt en skefuld røget paprika i saucen – det giver en dyb kødet smag selv uden kød.',
  dealItems: [
    { name: 'Grønne linser 250 g', store: 'Irma', price: '22 kr.' },
    { name: 'Fuldkornspasta 400 g', store: 'Fakta', price: '18 kr.' },
    { name: 'Hakkede tomater 2 dåser', store: 'Irma', price: '18 kr.' },
  ],
  dietaryFilters: ['Vegansk', 'Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Flæskesteg med Sprød Svær og Brun Sovs',
  emoji: '🌿', time: '90 minutter', servings_count: 6,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Den ultimative danske søndagssteg med knasende sprød svær og en dyb brun sovs. Hemmeligheden er salt i sværen og korrekt ovntemperatur. Serveret med rødkål og kartofler er dette den perfekte danske middag.',
  ingredients: [
    { text: 'Flæskesteg med svær 1,5 kg', store: 'Fakta', price: '75 kr.', isPantry: false },
    { text: 'Rødkål 1 glas syltet', store: 'Irma', price: '28 kr.', isPantry: false },
    { text: 'Kartofler 1,5 kg', store: 'Fakta', price: '18 kr.', isPantry: false },
    { text: 'Mel 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Oksefond 4 dl', store: null, price: null, isPantry: true },
    { text: 'Laurbær og allehånde', store: null, price: null, isPantry: true },
    { text: 'Groft salt', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær ridser i sværen ned til, men ikke igennem, kødet. Gnid groft salt ned i ridserne.',
    'Sæt stegen med sværen nedad i et fad med vand til det dækker sværen. Sæt i kold ovn, tænd ved 230°C i 30 minutter.',
    'Vend stegen med sværen opad. Steg videre ved 180°C i 60 minutter.',
    'Skru op til 250°C de sidste 15-20 minutter til sværen er sprød og boblende.',
    'Lav sovs af stegeskyen: brun mel i fedtet, tilsæt fond lidt ad gangen. Kog kartoflerne. Server.',
  ],
  tip: 'Sværen skal stikke med en nål eller gaffel inden stegning for at lade fedtet løbe ud – det er nøglen til den sprøde svær.',
  dealItems: [
    { name: 'Flæskesteg med svær 1,5 kg', store: 'Fakta', price: '75 kr.' },
    { name: 'Rødkål syltet', store: 'Irma', price: '28 kr.' },
    { name: 'Kartofler 1,5 kg', store: 'Fakta', price: '18 kr.' },
  ],
  dietaryFilters: [], difficulty: 'mellem',
},
{
  id: id(), title: 'Stegt Rødspætte med Remoulade og Citron',
  emoji: '🐟', time: '20 minutter', servings_count: 2,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'Sprød rødspætte vendt i mel og stegt gylden i smør serveret med en klat remoulade og en frisk citronbåd. En klassisk dansk sommerfrokost der er enkel i sin skønhed. Klar på 20 minutter.',
  ingredients: [
    { text: 'Rødspætte 2 stk.', store: 'Irma', price: '55 kr.', isPantry: false },
    { text: 'Remoulade 1 glas', store: 'Fakta', price: '18 kr.', isPantry: false },
    { text: 'Rugbrød til servering', store: 'Irma', price: '20 kr.', isPantry: false },
    { text: 'Mel til panering', store: null, price: null, isPantry: true },
    { text: 'Smør generøst', store: null, price: null, isPantry: true },
    { text: 'Citron 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Krydr rødspætterne med salt og peber og vend dem i mel.',
    'Smelt generøst smør i en stor pande ved middel-høj varme.',
    'Steg fiskene 3-4 minutter på hver side til gyldne og sprøde.',
    'Server straks med remoulade, citronbåde og rugbrød.',
  ],
  tip: 'Brug rigeligt smør – det er det der giver rødspætten dens karakteristiske gyldne farve og nøddeagtige smag.',
  dealItems: [
    { name: 'Rødspætte 2 stk.', store: 'Irma', price: '55 kr.' },
    { name: 'Remoulade', store: 'Fakta', price: '18 kr.' },
    { name: 'Rugbrød', store: 'Irma', price: '20 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Tomatsuppe med Fløde og Basilikum',
  emoji: '🍅', time: '30 minutter', servings_count: 4,
  category: 'Middelhavet', cuisine: '🇬🇷 Middelhavet',
  description: 'En silkeblød og cremet tomatsuppe med frisk basilikum og et drys parmesan. Enkel at lave men med en dybde der overrasker. Server med ristet hvidløgsbrød til at suge den skønne suppe op med.',
  ingredients: [
    { text: 'Hakkede tomater 3 dåser', store: 'Fakta', price: '24 kr.', isPantry: false },
    { text: 'Piskefløde 2 dl', store: 'Irma', price: '20 kr.', isPantry: false },
    { text: 'Frisk basilikum 1 bundt', store: 'Fakta', price: '12 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
    { text: 'Grøntsagsbouillon 4 dl', store: null, price: null, isPantry: true },
    { text: 'Sukker 1 tsk.', store: null, price: null, isPantry: true },
    { text: 'Olivenolie', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Svits løg og hvidløg i olivenolie 5 minutter.',
    'Tilsæt tomater, bouillon og sukker. Simr 15 minutter.',
    'Blend suppen glat med en stavblender.',
    'Tilsæt fløde og halvdelen af basilikumen, der er hakket groft. Varm igennem.',
    'Smag til med salt og peber. Server med resten af basilikumen og ristede brødet.',
  ],
  tip: 'En knivspids sukker neutraliserer syren fra tomaterne og giver suppen en rundere, blødere smag.',
  dealItems: [
    { name: 'Hakkede tomater 3 dåser', store: 'Fakta', price: '24 kr.' },
    { name: 'Piskefløde 2 dl', store: 'Irma', price: '20 kr.' },
    { name: 'Frisk basilikum', store: 'Fakta', price: '12 kr.' },
  ],
  dietaryFilters: ['Vegetar'], difficulty: 'nem',
},
{
  id: id(), title: 'Bøf Stroganoff med Jasminris',
  emoji: '🌿', time: '30 minutter', servings_count: 2,
  category: 'Europæisk', cuisine: '🇩🇰 Nordisk',
  description: 'Klassisk bøf stroganoff med møre oksekødstrimler i en cremet sennepssauce med svampe og løg. En rigtig trøstemad der er klar på 30 minutter og smager af søndag uanset hvilken dag det er.',
  ingredients: [
    { text: 'Okse- eller svinestrimler 350 g', store: 'Fakta', price: '42 kr.', isPantry: false },
    { text: 'Champignon 250 g', store: 'Irma', price: '22 kr.', isPantry: false },
    { text: 'Creme fraiche 200 g', store: 'Fakta', price: '16 kr.', isPantry: false },
    { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Dijonsennep 1 spsk.', store: null, price: null, isPantry: true },
    { text: 'Jasminris 200 g', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Kog risen. Steg kødet i portioner ved høj varme til brunet. Tag det op.',
    'Svits løg og champignon i smør 5 minutter.',
    'Tilsæt hvidløg, creme fraiche og sennep. Rør godt.',
    'Læg kødet tilbage og varm igennem. Smag til med salt og peber.',
    'Server stroganoff over jasminris.',
  ],
  tip: 'Steg aldrig alt kødet på en gang – overfyldt pande giver dampet, grå kød i stedet for brunet.',
  dealItems: [
    { name: 'Kødstrimler 350 g', store: 'Fakta', price: '42 kr.' },
    { name: 'Champignon 250 g', store: 'Irma', price: '22 kr.' },
    { name: 'Creme fraiche 200 g', store: 'Fakta', price: '16 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Kartoffelsuppe med Bacon og Creme Fraiche',
  emoji: '🌿', time: '35 minutter', servings_count: 4,
  category: 'Nordisk', cuisine: '🇩🇰 Nordisk',
  description: 'En hjertevarm og cremet kartoffelsuppe toppet med sprødt bacon og en skefuld syrlig creme fraiche. En billig og varmende hverdagssuppe der smager af komfort. Serveres med godt brød.',
  ingredients: [
    { text: 'Kartofler 1 kg', store: 'Fakta', price: '12 kr.', isPantry: false },
    { text: 'Bacon 200 g', store: 'Irma', price: '26 kr.', isPantry: false },
    { text: 'Creme fraiche 200 g', store: 'Fakta', price: '16 kr.', isPantry: false },
    { text: 'Løg 2 stk.', store: null, price: null, isPantry: true },
    { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
    { text: 'Grøntsagsbouillon 10 dl', store: null, price: null, isPantry: true },
    { text: 'Purløg til pynt', store: null, price: null, isPantry: true },
    { text: 'Salt og peber', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Skær bacon i tern og steg det sprødt. Tag det op og lad fedtet blive i gryden.',
    'Svits løg og hvidløg i baconfedtet 3 minutter.',
    'Tilsæt kartofler i tern og bouillon. Kog 20 minutter til kartoflerne er møre.',
    'Blend suppen glat. Smag til med salt og peber.',
    'Server med bacon, creme fraiche og snittede purløg på toppen.',
  ],
  tip: 'Tilsæt en klat smør i den blendede suppe for ekstra fylde og glans.',
  dealItems: [
    { name: 'Kartofler 1 kg', store: 'Fakta', price: '12 kr.' },
    { name: 'Bacon 200 g', store: 'Irma', price: '26 kr.' },
    { name: 'Creme fraiche 200 g', store: 'Fakta', price: '16 kr.' },
  ],
  dietaryFilters: [], difficulty: 'nem',
},
{
  id: id(), title: 'Vegetarisk Thai Grøntsagscurry med Ris',
  emoji: '🍛', time: '30 minutter', servings_count: 4,
  category: 'Asiatisk', cuisine: '🇯🇵 Asiatisk',
  description: 'En aromatisk og farverig thai-inspireret grøntsagscurry med kokosmælk, limeblade og frisk ingefær. Let, sund og fuld af friske smagsnuancer. Perfekt til at bruge de grøntsager du har i køleskabet.',
  ingredients: [
    { text: 'Kokosmælk 2 dåser', store: 'Irma', price: '38 kr.', isPantry: false },
    { text: 'Jasminris 300 g', store: 'Fakta', price: '16 kr.', isPantry: false },
    { text: 'Peberfrugt mix 3 stk.', store: 'Irma', price: '22 kr.', isPantry: false },
    { text: 'Grøn thaicurrypasta 2 spsk.', store: null, price: null, isPantry: true },
    { text: 'Ingefær 2 cm', store: null, price: null, isPantry: true },
    { text: 'Limesaft', store: null, price: null, isPantry: true },
    { text: 'Sojasauce', store: null, price: null, isPantry: true },
    { text: 'Frisk koriander', store: null, price: null, isPantry: true },
  ],
  steps: [
    'Svits currypasta og ingefær i lidt olivenolie 1 minut.',
    'Tilsæt kokosmælk og kog op.',
    'Tilsæt peberfrugt i strimler og kog 8-10 minutter til grøntsagerne er lidt møre men stadig har bid.',
    'Smag til med limesaft og sojasauce.',
    'Kog jasminris. Server curry over ris med frisk koriander.',
  ],
  tip: 'Tilsæt grøntsagerne gradvist efter tilberedningstid – hårde grøntsager først, bløde sidst.',
  dealItems: [
    { name: 'Kokosmælk 2 dåser', store: 'Irma', price: '38 kr.' },
    { name: 'Jasminris 300 g', store: 'Fakta', price: '16 kr.' },
    { name: 'Peberfrugt mix 3 stk.', store: 'Irma', price: '22 kr.' },
  ],
  dietaryFilters: ['Vegansk', 'Vegetar'], difficulty: 'nem',
},
];

const combined = [...existing, ...newRecipes];

// Summary
const CHAINS = ['Netto','Føtex','Bilka','Rema 1000','Coop 365',"SuperBrugsen / Kvickly","Dagli'Brugsen / Brugsen",'Meny','Spar','Eurospar','Lidl','Aldi','Fakta','Irma'];
console.log('\n--- Per-chain recipe count ---');
CHAINS.forEach(c => {
  const count = combined.filter(r => (r.dealItems||[]).some(d => d.store === c)).length;
  const ok = count >= 10 ? '✓' : '✗';
  console.log(`${ok} ${c.padEnd(30)} ${count}`);
});
console.log(`\nTotal recipes: ${combined.length}`);
console.log(`Added: ${newRecipes.length} new recipes`);

fs.writeFileSync(dataPath, JSON.stringify(combined, null, 2), 'utf8');
console.log('weeklyRecipes.json updated.');
