const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '../src/data/weeklyRecipes.json');
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const remaRecipes = [
  {
    title: 'Klassiske Frikadeller med Kartofler og Brun Sovs',
    emoji: '🌿',
    time: '45 minutter',
    servings_count: 4,
    category: 'Nordisk',
    cuisine: '🇩🇰 Nordisk',
    description: 'Hjemmelavede frikadeller af saftigt hakket svinekød serveret med kogte kartofler og en rig brun sovs. En klassisk dansk hverdagsret der samler familien om bordet. Enkel at tilberede og altid et hit hos børn og voksne.',
    ingredients: [
      { text: 'Hakket svinekød 500 g', store: 'Rema 1000', price: '28 kr.', isPantry: false },
      { text: 'Kartofler 1,5 kg', store: 'Rema 1000', price: '15 kr.', isPantry: false },
      { text: 'Løg 2 stk.', store: 'Rema 1000', price: '8 kr.', isPantry: false },
      { text: 'Æg 1 stk.', store: null, price: null, isPantry: true },
      { text: 'Mel 2 spsk.', store: null, price: null, isPantry: true },
      { text: 'Mælk 1 dl', store: null, price: null, isPantry: true },
      { text: 'Smør til stegning', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Hak løget fint og bland det med hakket svinekød, æg, mel og mælk. Krydr godt med salt og peber.',
      'Lad farsen hvile i køleskabet i 10 minutter så den sætter sig.',
      'Form frikadeller med en ske og steg dem i smør på middel varme, 4-5 minutter på hver side til de er gyldne og gennemstegte.',
      'Kog kartoflerne i letsaltet vand i 20 minutter til de er møre.',
      'Lav sovs ved at brune mel i stegefedtet, tilsæt vand eller fond lidt ad gangen under omrøring til sovsen er jævn og blank.',
      'Smag sovsen til med salt og peber og server med frikadellerne og kartoflerne.',
    ],
    tip: 'Tilsæt lidt revet muskatnød i farsen for ekstra dybde. Frikadeller smager også godt kolde dagen efter.',
    dealItems: [
      { name: 'Hakket svinekød 500 g', store: 'Rema 1000', price: '28 kr.' },
      { name: 'Kartofler 1,5 kg', store: 'Rema 1000', price: '15 kr.' },
      { name: 'Løg 2 stk.', store: 'Rema 1000', price: '8 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Ovnbagt Kylling med Rodfrugter og Timian',
    emoji: '🌿',
    time: '55 minutter',
    servings_count: 4,
    category: 'Nordisk',
    cuisine: '🇩🇰 Nordisk',
    description: 'Saftige kyllingelår bagt gyldne i ovnen sammen med karamelliserede rodfrugter og frisk timian. En nem ovnret der passer sig selv mens du laver andet. Fyldig smag med minimal indsats.',
    ingredients: [
      { text: 'Kyllingelår 1 kg', store: 'Rema 1000', price: '39 kr.', isPantry: false },
      { text: 'Gulerødder 500 g', store: 'Rema 1000', price: '10 kr.', isPantry: false },
      { text: 'Kartofler 750 g', store: 'Rema 1000', price: '12 kr.', isPantry: false },
      { text: 'Rødløg 2 stk.', store: 'Rema 1000', price: '9 kr.', isPantry: false },
      { text: 'Hvidløg 4 fed', store: null, price: null, isPantry: true },
      { text: 'Timian frisk eller tørret', store: null, price: null, isPantry: true },
      { text: 'Olivenolie 3 spsk.', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Forvarm ovnen til 200°C varmluft.',
      'Skær kartofler og gulerødder i grove stykker, rødløg i både. Læg det hele i et stort ildfast fad.',
      'Læg kyllingelårene oven på grøntsagerne. Drys med timian, salt og peber, og dryp med olivenolie.',
      'Fordel hele hvidløgsfed rundt i fadet.',
      'Bag i ovnen i 45-50 minutter til kyllingen er gylden og grøntsagerne er bløde og let karamelliserede.',
      'Lad retten hvile 5 minutter inden servering. Server direkte fra fadet.',
    ],
    tip: 'Pres det bagte hvidløg ud af skallen og smør det på brødet som en naturlig creme – det er vidunderligt sødt og blødt.',
    dealItems: [
      { name: 'Kyllingelår 1 kg', store: 'Rema 1000', price: '39 kr.' },
      { name: 'Gulerødder 500 g', store: 'Rema 1000', price: '10 kr.' },
      { name: 'Kartofler 750 g', store: 'Rema 1000', price: '12 kr.' },
      { name: 'Rødløg 2 stk.', store: 'Rema 1000', price: '9 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Tacos med Hakket Oksekød og Frisk Salsa',
    emoji: '🌮',
    time: '30 minutter',
    servings_count: 4,
    category: 'Mexicansk',
    cuisine: '🇲🇽 Mexicansk',
    description: 'Sprøde tacos fyldt med krydret hakket oksekød og en frisk hjemmelavet tomatsalsa. En festlig hverdagsret der kan sættes på bordet på under 30 minutter. Alle kan bygge deres egne tacos – perfekt til familien.',
    ingredients: [
      { text: 'Hakket oksekød 400 g', store: 'Rema 1000', price: '32 kr.', isPantry: false },
      { text: 'Tortilla wraps 8 stk.', store: 'Rema 1000', price: '18 kr.', isPantry: false },
      { text: 'Tomater 4 stk.', store: 'Rema 1000', price: '16 kr.', isPantry: false },
      { text: 'Peberfrugt 1 stk.', store: 'Rema 1000', price: '12 kr.', isPantry: false },
      { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
      { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
      { text: 'Spidskommen, paprika, chili', store: null, price: null, isPantry: true },
      { text: 'Limesaft', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Hak tomater og peberfrugt fint til salsa. Bland med limesaft, salt og et nip chili. Stil til side.',
      'Svits hakket løg og hvidløg i en pande til det er blødt.',
      'Tilsæt oksekødet og steg ved høj varme til alt er brunet. Krydr med spidskommen, paprika, chili, salt og peber.',
      'Varm tortillaerne i en tør pande eller mikroovn i 20 sekunder.',
      'Fyld tortillaerne med oksekødsblandingen og top med frisk salsa.',
      'Server med rømme og guacamole hvis du har det.',
    ],
    tip: 'Giv kødet 2 minutter ekstra på panden uden at røre det til sidst – det giver en lækker stegt skorpe på farsen.',
    dealItems: [
      { name: 'Hakket oksekød 400 g', store: 'Rema 1000', price: '32 kr.' },
      { name: 'Tortilla wraps 8 stk.', store: 'Rema 1000', price: '18 kr.' },
      { name: 'Tomater 4 stk.', store: 'Rema 1000', price: '16 kr.' },
      { name: 'Peberfrugt 1 stk.', store: 'Rema 1000', price: '12 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Cremet Laksepasta med Citron og Kapers',
    emoji: '🍝',
    time: '25 minutter',
    servings_count: 2,
    category: 'Italiensk',
    cuisine: '🇮🇹 Italiensk',
    description: 'Al dente pasta med flager af laks i en silkeblød flødesauce med frisk citron og salte kapers. En elegant ret der er klar på under 25 minutter. Perfekt til en afslappet aften hvor du vil have noget lækkert uden besvær.',
    ingredients: [
      { text: 'Laksesteak 300 g', store: 'Rema 1000', price: '45 kr.', isPantry: false },
      { text: 'Pasta 300 g', store: 'Rema 1000', price: '12 kr.', isPantry: false },
      { text: 'Piskefløde 2 dl', store: 'Rema 1000', price: '15 kr.', isPantry: false },
      { text: 'Kapers 1 spsk.', store: null, price: null, isPantry: true },
      { text: 'Citronskal og -saft fra 1 citron', store: null, price: null, isPantry: true },
      { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
      { text: 'Olivenolie', store: null, price: null, isPantry: true },
      { text: 'Dild frisk eller tørret', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Kog pasta efter pakkens anvisning i godt saltet vand. Gem 1 dl pastavand inden afvanding.',
      'Krydr laksen med salt og peber og steg den i olivenolie 3-4 minutter på hver side til den er gennemstegt. Lad den hvile og flak den groft.',
      'Svits hvidløg i samme pande i 30 sekunder. Tilsæt fløde og lad det reducere 2-3 minutter.',
      'Tilsæt citronskal, citronsaft og kapers. Smag til med salt og peber.',
      'Vend den kogte pasta i saucen. Tilsæt lidt pastavand hvis saucen er for tyk.',
      'Anret med lakseflager på toppen og drys med frisk dild.',
    ],
    tip: 'Brug aldrig frosset laks direkte – lad den tø op i køleskabet natten over for det bedste resultat.',
    dealItems: [
      { name: 'Laksesteak 300 g', store: 'Rema 1000', price: '45 kr.' },
      { name: 'Pasta 300 g', store: 'Rema 1000', price: '12 kr.' },
      { name: 'Piskefløde 2 dl', store: 'Rema 1000', price: '15 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Kyllingekurry med Basmatiris og Kokosmælk',
    emoji: '🍛',
    time: '35 minutter',
    servings_count: 4,
    category: 'Indisk',
    cuisine: '🇮🇳 Indisk',
    description: 'En velsmagende kyllingekurry kogt med kokosmælk og aromatiske krydderier serveret med luftigt basmatiris. Retten er mild nok til hele familien men med masser af dybde og karakter. En aften i Indiens tegn behøver ikke tage lang tid.',
    ingredients: [
      { text: 'Kyllingebryst 600 g', store: 'Rema 1000', price: '49 kr.', isPantry: false },
      { text: 'Kokosmælk 400 ml dåse', store: 'Rema 1000', price: '22 kr.', isPantry: false },
      { text: 'Basmatiris 300 g', store: 'Rema 1000', price: '18 kr.', isPantry: false },
      { text: 'Løg 2 stk.', store: 'Rema 1000', price: '8 kr.', isPantry: false },
      { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
      { text: 'Ingefær frisk 1 tsk.', store: null, price: null, isPantry: true },
      { text: 'Karry, gurkemeje, garam masala', store: null, price: null, isPantry: true },
      { text: 'Hakkede tomater halvdåse', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Skær kyllingebrystet i mundrette stykker og krydr med salt og peber.',
      'Svits hakket løg, hvidløg og ingefær i olie ved middel varme i 5 minutter.',
      'Tilsæt karry, gurkemeje og garam masala og steg krydderierne 1 minut under omrøring.',
      'Tilsæt kyllingen og brun den 3-4 minutter. Tilsæt hakkede tomater og kokosmælk.',
      'Lad retten simre uden låg i 20 minutter til saucen er tyknet og kyllingen er mør.',
      'Kog basmatiris efter pakkens anvisning og server med karryen.',
    ],
    tip: 'Tilsæt en håndfuld frisk spinat de sidste 2 minutter for farve og næringsstoffer uden at ændre smagen.',
    dealItems: [
      { name: 'Kyllingebryst 600 g', store: 'Rema 1000', price: '49 kr.' },
      { name: 'Kokosmælk 400 ml', store: 'Rema 1000', price: '22 kr.' },
      { name: 'Basmatiris 300 g', store: 'Rema 1000', price: '18 kr.' },
      { name: 'Løg 2 stk.', store: 'Rema 1000', price: '8 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Svinekam med Æbler, Rødkål og Brunede Kartofler',
    emoji: '🌿',
    time: '70 minutter',
    servings_count: 4,
    category: 'Nordisk',
    cuisine: '🇩🇰 Nordisk',
    description: 'En klassisk søndagsmiddag med saftig svinekam, syrlig rødkål og søde brunede kartofler. Kombinationen af sødt og salt er typisk dansk og giver en dejlig balanceret middag. Perfekt til familiemiddagen i weekenden.',
    ingredients: [
      { text: 'Svinekam uden ben 1 kg', store: 'Rema 1000', price: '59 kr.', isPantry: false },
      { text: 'Rødkål 800 g', store: 'Rema 1000', price: '14 kr.', isPantry: false },
      { text: 'Kartofler 1 kg', store: 'Rema 1000', price: '12 kr.', isPantry: false },
      { text: 'Æbler 2 stk.', store: 'Rema 1000', price: '10 kr.', isPantry: false },
      { text: 'Sukker 3 spsk.', store: null, price: null, isPantry: true },
      { text: 'Smør 50 g', store: null, price: null, isPantry: true },
      { text: 'Rødvinseddike 2 spsk.', store: null, price: null, isPantry: true },
      { text: 'Laurbær, allehånde, nellike', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Forvarm ovnen til 180°C. Krydr svinekammen generøst med salt og peber og brun den i en pande i smør på alle sider.',
      'Læg svinekammen i et ildfast fad og sæt den i ovnen i 50-60 minutter til kernetemperaturen er 65°C.',
      'Snit rødkålen fint og kog den med eddike, sukker, laurbær og krydderier i 30 minutter til den er mør.',
      'Kog kartoflerne og brun dem i sukker og smør i en pande til de er gyldne og karamelliserede.',
      'Skær æblerne i både og steg dem kort i smør med lidt sukker til de er bløde.',
      'Lad svinekammen hvile 10 minutter inden udskæring. Server det hele samlet.',
    ],
    tip: 'Brug saften fra stegen til en hurtig sovs: tilsæt lidt vand og fond, kog op og jævn med maizena.',
    dealItems: [
      { name: 'Svinekam uden ben 1 kg', store: 'Rema 1000', price: '59 kr.' },
      { name: 'Rødkål 800 g', store: 'Rema 1000', price: '14 kr.' },
      { name: 'Kartofler 1 kg', store: 'Rema 1000', price: '12 kr.' },
      { name: 'Æbler 2 stk.', store: 'Rema 1000', price: '10 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'mellem',
  },
  {
    title: 'Hjemmelavet Burger med Cheddar og Karamelliseret Løg',
    emoji: '🍔',
    time: '30 minutter',
    servings_count: 4,
    category: 'Amerikansk',
    cuisine: '🇺🇸 Amerikansk',
    description: 'Saftige hjemmelavede burgerbøffer med smeltet cheddar og søde karamelliserede løg i bløde burgerboller. Langt bedre end fast food og klar på 30 minutter. En fredag-aften favorit der gør alle glade.',
    ingredients: [
      { text: 'Hakket oksekød 600 g', store: 'Rema 1000', price: '38 kr.', isPantry: false },
      { text: 'Burgerboller 4 stk.', store: 'Rema 1000', price: '19 kr.', isPantry: false },
      { text: 'Cheddarost 4 skiver', store: 'Rema 1000', price: '24 kr.', isPantry: false },
      { text: 'Løg 2 store', store: 'Rema 1000', price: '9 kr.', isPantry: false },
      { text: 'Smør 1 spsk.', store: null, price: null, isPantry: true },
      { text: 'Sukker 1 tsk.', store: null, price: null, isPantry: true },
      { text: 'Mayonnaise og ketchup', store: null, price: null, isPantry: true },
      { text: 'Salt og peber', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Skær løgene i tynde ringe og steg dem i smør på lav varme i 20 minutter under omrøring. Tilsæt sukker de sidste 5 minutter.',
      'Form oksekødet til 4 bøffer på ca. 150 g. Krydr med salt og peber på begge sider.',
      'Steg bøfferne på en varm pande 3-4 minutter på hver side.',
      'Læg cheddar på bøfferne det sidste minut og læg låg på panden så osten smelter.',
      'Rist burgerbollerne i smøret fra løgene.',
      'Byg burgerne: bund, sauce, bøffe med smeltet ost, karamelliserede løg og top.',
    ],
    tip: 'Brug 20% fedt i kødet for en saftig burger. Tryk ikke på bøffen mens den steger – det presser saften ud.',
    dealItems: [
      { name: 'Hakket oksekød 600 g', store: 'Rema 1000', price: '38 kr.' },
      { name: 'Burgerboller 4 stk.', store: 'Rema 1000', price: '19 kr.' },
      { name: 'Cheddarost 4 skiver', store: 'Rema 1000', price: '24 kr.' },
      { name: 'Løg 2 store', store: 'Rema 1000', price: '9 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Grøntsagssuppe med Linser og Chorizo',
    emoji: '🫒',
    time: '40 minutter',
    servings_count: 4,
    category: 'Middelhavet',
    cuisine: '🇬🇷 Middelhavet',
    description: 'En varmende og mættende suppe med røde linser, røget chorizo og massevis af grøntsager. Fuld af protein og smag fra de krydrede pølser. Perfekt til en kold dag og endnu bedre som rester dagen efter.',
    ingredients: [
      { text: 'Chorizo pølse 200 g', store: 'Rema 1000', price: '28 kr.', isPantry: false },
      { text: 'Røde linser 200 g', store: 'Rema 1000', price: '14 kr.', isPantry: false },
      { text: 'Gulerødder 3 stk.', store: 'Rema 1000', price: '8 kr.', isPantry: false },
      { text: 'Selleri 2 stængler', store: 'Rema 1000', price: '10 kr.', isPantry: false },
      { text: 'Løg 1 stk.', store: null, price: null, isPantry: true },
      { text: 'Hvidløg 3 fed', store: null, price: null, isPantry: true },
      { text: 'Hakkede tomater 1 dåse', store: null, price: null, isPantry: true },
      { text: 'Grøntsagsbouillon 1 L', store: null, price: null, isPantry: true },
      { text: 'Paprika, spidskommen', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Skær chorizo i skiver og steg dem i en gryde til de er sprøde. Tag dem op og læg til side.',
      'Svits hakket løg, hvidløg, gulerødder og selleri i pølsefedtet i 5 minutter.',
      'Tilsæt paprika og spidskommen og steg 1 minut.',
      'Tilsæt linser, hakkede tomater og bouillon. Kog op og lad det simre 25 minutter til linserne er møre.',
      'Smag til med salt og peber. Blend halvdelen af suppen for en cremet konsistens.',
      'Server med chorizo-skiverne på toppen og et godt stykke brød ved siden af.',
    ],
    tip: 'Linserne tykner suppen kraftigt når den køler – tilsæt ekstra vand ved opvarmning af rester.',
    dealItems: [
      { name: 'Chorizo pølse 200 g', store: 'Rema 1000', price: '28 kr.' },
      { name: 'Røde linser 200 g', store: 'Rema 1000', price: '14 kr.' },
      { name: 'Gulerødder 3 stk.', store: 'Rema 1000', price: '8 kr.' },
      { name: 'Selleri 2 stængler', store: 'Rema 1000', price: '10 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'nem',
  },
  {
    title: 'Bagte Grøntsager med Fetacreme og Fuldkornsbrød',
    emoji: '🫒',
    time: '35 minutter',
    servings_count: 2,
    category: 'Middelhavet',
    cuisine: '🇬🇷 Middelhavet',
    description: 'Farverige ovnbagte grøntsager med en luftig fetacreme og ristet fuldkornsbrød. En let og nærende vegetarret der er smuk på tallerkenen og fyldig i smagen. Perfekt som et sundt hverdagsalternativ.',
    ingredients: [
      { text: 'Feta 200 g', store: 'Rema 1000', price: '26 kr.', isPantry: false },
      { text: 'Peberfrugt mix 3 stk.', store: 'Rema 1000', price: '22 kr.', isPantry: false },
      { text: 'Zucchini 2 stk.', store: 'Rema 1000', price: '14 kr.', isPantry: false },
      { text: 'Fuldkornsbrød 4 skiver', store: 'Rema 1000', price: '16 kr.', isPantry: false },
      { text: 'Hvidløg 2 fed', store: null, price: null, isPantry: true },
      { text: 'Olivenolie 3 spsk.', store: null, price: null, isPantry: true },
      { text: 'Timian og oregano', store: null, price: null, isPantry: true },
      { text: 'Citron halvt stk.', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Forvarm ovnen til 220°C.',
      'Skær peberfrugter og zucchini i grove stykker. Vend dem med olivenolie, timian, oregano, salt og peber.',
      'Bred grøntsagerne ud på en bageplade og bag 25 minutter til de er let karamelliserede og bløde.',
      'Blend feta med hvidløg, lidt olivenolie og citronsaft til en glat creme. Krydr med peber.',
      'Rist brødskiverne i en tør pande eller ovn.',
      'Smør fetacremen på brødet og top med de bagte grøntsager. Dryp med olivenolie og server straks.',
    ],
    tip: 'Fetacremen kan laves i forvejen og holdes i køleskabet i op til 3 dage – god til sandwich og wraps.',
    dealItems: [
      { name: 'Feta 200 g', store: 'Rema 1000', price: '26 kr.' },
      { name: 'Peberfrugt mix 3 stk.', store: 'Rema 1000', price: '22 kr.' },
      { name: 'Zucchini 2 stk.', store: 'Rema 1000', price: '14 kr.' },
      { name: 'Fuldkornsbrød 4 skiver', store: 'Rema 1000', price: '16 kr.' },
    ],
    dietaryFilters: ['Vegetar'],
    difficulty: 'nem',
  },
  {
    title: 'Pasta Carbonara med Bacon og Parmesan',
    emoji: '🍝',
    time: '20 minutter',
    servings_count: 2,
    category: 'Italiensk',
    cuisine: '🇮🇹 Italiensk',
    description: 'Den klassiske romerske pasta carbonara med sprødt bacon, cremede æg og revet parmesan – lavet uden fløde som det gøres i Rom. Utrolig simpel og utrolig god. Klar på 20 minutter med ingredienser du altid har hjemme.',
    ingredients: [
      { text: 'Bacon 200 g', store: 'Rema 1000', price: '24 kr.', isPantry: false },
      { text: 'Spaghetti 300 g', store: 'Rema 1000', price: '12 kr.', isPantry: false },
      { text: 'Parmesan 60 g revet', store: 'Rema 1000', price: '22 kr.', isPantry: false },
      { text: 'Æg 3 stk. samt 2 æggeblommer', store: null, price: null, isPantry: true },
      { text: 'Hvidløg 1 fed', store: null, price: null, isPantry: true },
      { text: 'Sort peber', store: null, price: null, isPantry: true },
      { text: 'Salt', store: null, price: null, isPantry: true },
    ],
    steps: [
      'Kog spaghetti i rigeligt saltet vand til al dente. Gem 200 ml pastavand inden afvanding.',
      'Skær bacon i strimler og steg dem i en stor pande til de er sprøde. Tilsæt knust hvidløg de sidste 30 sekunder.',
      'Pisk æg, æggeblommer og det meste af parmesanen sammen. Krydr generøst med sort peber.',
      'Tag panden af varmen. Tilsæt den varme pasta og rør hurtigt.',
      'Hæld æggeblandingen over pastaen og rør hurtigt mens du tilsætter lidt pastavand ad gangen til saucen er cremet og blank.',
      'Server straks toppet med resten af parmesanen og rigeligt sort peber.',
    ],
    tip: 'Hemmeligheden er at tage panden af varmen før æggeblandingen tilsættes – ellers får du røræg i stedet for sauce.',
    dealItems: [
      { name: 'Bacon 200 g', store: 'Rema 1000', price: '24 kr.' },
      { name: 'Spaghetti 300 g', store: 'Rema 1000', price: '12 kr.' },
      { name: 'Parmesan 60 g', store: 'Rema 1000', price: '22 kr.' },
    ],
    dietaryFilters: [],
    difficulty: 'mellem',
  },
];

const startId = existing.length; // 41 → first new ID = 1041
const newRecipes = remaRecipes.map((r, i) => ({ id: 1000 + startId + i, ...r }));
const combined = [...existing, ...newRecipes];

// Verify
const remaTotal = combined.filter(r => (r.dealItems || []).some(d => d.store === 'Rema 1000'));
const nettoTotal = combined.filter(r => (r.dealItems || []).some(d => d.store === 'Netto'));
const coopTotal = combined.filter(r => (r.dealItems || []).some(d => d.store === 'Coop 365'));

console.log('--- Chain summary ---');
console.log(`Rema 1000: ${remaTotal.length}/10`);
console.log(`Netto:     ${nettoTotal.length}/10`);
console.log(`Coop 365:  ${coopTotal.length}/10`);
console.log(`Total recipes: ${combined.length}`);
console.log(`New IDs: ${newRecipes[0].id} – ${newRecipes[newRecipes.length - 1].id}`);

fs.writeFileSync(dataPath, JSON.stringify(combined, null, 2), 'utf8');
console.log('weeklyRecipes.json updated.');
